### ISSUE TITLE
About README

### ISSUE THREAD

**Issue by hiroyuki-sato** [celluloid/timeout-extensions#3]
Hello

## Timeout::timeout?

In the following example,  Timeout::timeout(30) instead of Timeout.new?

There are two parts.

First one

```ruby
require 'timeout/extensions'

Timeout.new(30) do # <-- HERE
  # Times out after 30 seconds raising Timeout::Error
end
```

Anothr one.

```ruby
Timeout.backend(MyTimeoutThingy) do
  Timeout.new(30) do # <-- HERE
    # Manage timeouts with MyTimeoutThingy instead of timeout.rb
    # Plug in your own backend just this easily!
  end
end
```

## require 'timeout' need?

Error

```shell
ruby test.rb 
/usr/local/ruby20/lib/ruby/gems/2.2.0/gems/timeout-extensions-0.0.0/lib/timeout/extensions/version.rb:1:in `<top (required)>': uninitialized constant Timeout (NameError)
	from /usr/local/ruby20/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/ruby20/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/ruby20/lib/ruby/gems/2.2.0/gems/timeout-extensions-0.0.0/lib/timeout/extensions.rb:1:in `<top (required)>'
	from /usr/local/ruby20/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/local/ruby20/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/ruby20/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from test.rb:2:in `<main>'
```  

Code

```ruby
#require 'timeout'
require 'timeout/extensions'

module MyTimeoutThingy
  # WARNING: don't use this. It's just a strawman example
  def self.timeout(secs)
    current = Thread.current
    sleeper = Thread.start do
      begin
        sleep secs
      rescue => ex
        current.raise ex
      else
        current.raise Timeout::Error, "execution expired" 
      end
    end
    return yield(secs)
  ensure
    if sleeper
      sleeper.kill
      sleeper.join
    end
  end
end

Timeout.backend(MyTimeoutThingy) do
#  Timeout.new(30) do
  Timeout.timeout(30) do
    # Manage timeouts with MyTimeoutThingy instead of timeout.rb
    # Plug in your own backend just this easily!
  end
end
```    
    
The following error still raised.    

```shell
test.rb:26:in `<main>': undefined method `backend' for Timeout:Module (NoMethodError)
```

Hiroyuki Sato.

**Comment by wildlyinaccurate** [comment]
I was having similar issues. I think my runtime is confusing this Gem with [stdlib-timeout](http://www.ruby-doc.org/stdlib-2.2.0/libdoc/timeout/rdoc/Timeout.html)?

**Comment by tarcieri** [comment]
Please confirm this is still an issue
